package com.shellycoffee.timer

import com.shellycoffee.timer.api.MqttTls
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * JVM unit tests for the pure mTLS builder (no Android deps). Uses throwaway fixtures generated by
 * OpenSSL (test_ca.crt = self-signed CA, test_client.p12 = client identity signed by it, pass "testpass").
 * Run: ./gradlew testDebugUnitTest
 */
class MqttTlsTest {

    private fun res(name: String): ByteArray =
        javaClass.getResourceAsStream("/$name")?.readBytes()
            ?: error("missing test fixture: $name")

    private val ca get() = res("test_ca.crt")
    private val p12 get() = res("test_client.p12")
    private val pass get() = "testpass".toCharArray()

    @Test fun buildsFactoryFromValidCaAndClient() {
        assertNotNull("valid CA + client p12 should yield a socket factory",
            MqttTls.buildSocketFactory(ca, p12, pass))
    }

    @Test fun nullOnGarbageCa() {
        assertNull("garbage CA bytes must not throw, must return null",
            MqttTls.buildSocketFactory("not a certificate".toByteArray(), p12, pass))
    }

    @Test fun nullOnEmptyCa() {
        assertNull(MqttTls.buildSocketFactory(ByteArray(0), p12, pass))
    }

    @Test fun nullOnWrongP12Password() {
        assertNull("wrong PKCS#12 password must return null",
            MqttTls.buildSocketFactory(ca, p12, "wrongpass".toCharArray()))
    }

    @Test fun nullOnGarbageP12() {
        assertNull(MqttTls.buildSocketFactory(ca, "not a p12".toByteArray(), pass))
    }
}
